### ISSUE TITLE
Update the binaries name in the release page

### ISSUE THREAD

**Issue by pythops** [Jguer/yay#1653]
Hi

It would be nice to add binaries in the releases page that have the name in this format : `yay_latest_<arch>.tar.gz`, so there is a permanent link that  always point to the latest release  `https://github.com/Jguer/yay/releases/latest/download/yay_latest_x86_64.tar.gz`.

Thanks

**Comment by Jguer** [comment]
I agree it is nice, but is there a why to justify this change?

**Comment by pythops** [comment]
The reason why I asked for this is that I use `ansible` to install `yay`.
```
- name: Install yay
  ansible.builtin.unarchive:
    src: https://github.com/Jguer/yay/releases/download/v11.0.2/yay_11.0.2_x86_64.tar.gz
    dest: /usr/bin
    remote_src: yes
    include: yay_11.0.2_x86_64/yay
    extra_opts:
      - --strip-components=1
    mode: 0755
  become: yes
  ```
  And by having `latest` instead of the version, whenever I run this task I'm sure I'll always get the latest version available.
